################################################################################
# Espressif ESP32 C3 Super Mini v1
################################################################################
# The components used are:
#     - Generic ESP32-C3 OLED 0.42" Display
#         - Enabled hardware and services:
#             - WiFi
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# Notes: 
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
# Use at your own risks!
################################################################################

################################################################################
# Substitution Variables
################################################################################
substitutions:
  device_internal_name: esphome_c3_oled
  device_wifi_name: esphome-c3-oled
  device_friendly_name: Generic ESP32-C3 OLED 0.42" Display
  device_ip_address: 192.168.5.102
  device_sampling_time: 30s
  region: Africa/Johannesburg

################################################################################
# Packages
################################################################################
packages:
  # ----------------------------------------------------------------------------
  # Core packages
  # ----------------------------------------------------------------------------
  board: !include boards/esp32/c3-oled-0-42-display.yaml
  settings: !include common/core/settings.yaml
  time: !include common/time/home_assistant.yaml

  # Network
  wifi: !include common/network/wifi.yaml
  webserver: !include common/network/webserver.yaml

  # Display
  font: !include common/display/fonts.yaml
  color: !include common/display/colors.yaml
  glyphs: !include common/display/glyphs.yaml
  display: !include 
    file: peripherals/display/ssd1306_0_42_oled_i2c.yaml
    vars:
      i2c_address: 0x3c

################################################################################
# Board Configuration
################################################################################
esphome:
  comment: ABRobot ESP32-C3 OLED 0.42" Display

################################################################################
# Custom Device Configuration
################################################################################

# -------------------------------------------------------------------------------
# Remove existing configurations
# -------------------------------------------------------------------------------
