################################################################################
# Substitution Variables
################################################################################
substitutions:
  device_internal_name: esphome_esp32c6_calibration
  device_wifi_name: esphome-esp32c6-calibration
  device_friendly_name: ESPHome ESP32 C6 Calibration
  device_ip_address: 192.168.0.46
  device_sampling_time: 30s
  region: Africa/Johannesburg

################################################################################
# Packages
################################################################################
packages:
  # ----------------------------------------------------------------------------
  # ESP32 Internal Board Configurations packages
  # ----------------------------------------------------------------------------

  # ----------------------------------------------------------------------------
  # Additional Peripherals
  # ----------------------------------------------------------------------------

  # ----------------------------------------------------------------------------
  # Sensor packages
  # ----------------------------------------------------------------------------
  

################################################################################
# Board Configuration
################################################################################
esphome:
  name: ${device_internal_name}
  friendly_name: ${device_friendly_name}

################################################################################
# Custom Device Configuration
################################################################################
